{% set name = "lmfit" %}
{% set version = "1.0.2" %}
{% set sha256 = "67090ce56685cf7f92bd7358a1e7d4ad862b3758988109ec440e9825e5184b45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.5
    - asteval >=0.9.16
    - numpy >=1.16
    - scipy >=1.2
    - six
    - uncertainties >=3.0.1

test:
  imports:
    - {{ name }}

about:
  home: http://lmfit.github.io/lmfit-py
  license: lmfit
  license_family: BSD
  license_file: LICENSE
  summary: >
    Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize.leastsq, and with many additional classes and methods for curve fitting http://lmfit.github.io/lmfit-py.
